# Generated by Django 4.2.7 on 2023-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.CharField(max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='links',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Короткая ссылка'),
        ),
    ]
