# Generated by Django 4.2.7 on 2023-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_links_link_alter_links_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(max_length=250, verbose_name='Ссылка (до 250 символов)'),
        ),
        migrations.AlterField(
            model_name='links',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
