# Generated by Django 4.2.7 on 2023-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_links_link_alter_links_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
